using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEngine.InputSystem;

public class TutorialTextController : MonoBehaviour
{
    RectTransform rect;
    public TextMeshProUGUI tutotext;

    public int textnumber = 0; // ï¿½eï¿½Lï¿½Xï¿½gï¿½Ì”Ôï¿½
    private string[] textlist = {"Qã‚­ãƒ¼ã‚’æŠ¼ã—ã¦ã„ã‚‹é–“ã€ã‚¸ãƒ³ãƒ™ã‚¨ã‚¶ãƒ¡ã‚’ä½¿ãˆã‚‹ã‚ˆï¼","Qã‚­ãƒ¼ã‚’æŠ¼ã—ãªãŒã‚‰ã€\nè½ã¡ã¦ã„ã‚‹ã‚´ãƒŸã«è¿‘ã¥ã„ã¦ã¿ã‚ˆã†ï¼"};

    [SerializeField] public float max_position_x = -200f; // ï¿½eï¿½Lï¿½Xï¿½gï¿½ï¿½ï¿½Ú“ï¿½ï¿½Å‚ï¿½ï¿½ï¿½Eï¿½[
    [SerializeField] public float min_position_x = -2000f; // ï¿½eï¿½Lï¿½Xï¿½gï¿½ï¿½ï¿½Ú“ï¿½ï¿½Å‚ï¿½ï¿½é¶ï¿½[
    [SerializeField] public bool isEntering = true; // ï¿½eï¿½Lï¿½Xï¿½gï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½ï¿½\ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
    [SerializeField] public bool isOutgoing = false; // ï¿½eï¿½Lï¿½Xï¿½gï¿½ï¿½ï¿½Şê’†ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O

    // Start is called before the first frame update
    void Start()
    {
        rect = GetComponent<RectTransform>();
    }

    // Update is called once per frame
    void Update()
    {
        // textnumberï¿½Ì’lï¿½É‚ï¿½ï¿½ï¿½Äƒeï¿½Lï¿½Xï¿½gï¿½Ì“ï¿½ï¿½eï¿½ï¿½ÏX tutolistï¿½ï¿½(textnumber + 1)ï¿½Ô–Ú‚Ìƒeï¿½Lï¿½Xï¿½gï¿½ï¿½\ï¿½ï¿½
        if (0 <= textnumber && textnumber < textlist.Length)
        {
            tutotext.text = textlist[textnumber];
        }

        // max_position_xï¿½Ü‚ï¿½ï¿½ï¿½min_poisition_xï¿½Ü‚Åƒeï¿½Lï¿½Xï¿½gï¿½ï¿½ï¿½Ú“ï¿½
        if (isEntering == true)
        {
            rect.anchoredPosition += new Vector2(5, 0);
        }
        if (isOutgoing == true)
        {
            rect.anchoredPosition += new Vector2(-5, 0);
        }

        // max_potition_xï¿½Ü‚ï¿½ï¿½ï¿½min_potition_xï¿½ğ’´‚ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½ï¿½ï¿½~
        if (rect.anchoredPosition.x >= max_position_x)
        {
            isEntering = false;
        }
        if (rect.anchoredPosition.x <= min_position_x)
        {
            isOutgoing = false;
        }
        
    }
}
